---
- name: include pip vars
  include_vars: pip-{{ cm_pip_source }}.yml
  when: cm_pip_host is not defined

- name: create .pip directory
  file:
    path='~/.config/pip'
    state=directory

- name: config pip mirror
  template:
    src=pip.conf.j2
    dest='~/.config/pip/pip.conf'
