---
- name: include apt vars
  include_vars: apt-{{ apt_source }}.yml
  when: apt_host is not defined

- name: config apt mirror
  become: yes
  template:
    src=sources.list.j2
    dest=/etc/apt/sources.list
    backup=yes
  notify: update cache

- name: install apt-transport-https
  become: yes
  apt:
    name=apt-transport-https
    state=present
