---
- name: include apt vars
  include_vars: apt-{{ cm_apt_source }}.yml
  when: cm_apt_host is not defined

- name: config apt mirror
  template:
    src=sources.list.j2
    dest=/etc/apt/sources.list
    backup=yes
  notify: update cache

# - name: install apt-transport-https
#   apt:
#     name=apt-transport-https
#     state=present
